### ISSUE TITLE
error launching kernel

### ISSUE THREAD

**Issue by elbamos** [pprzetacznik/IElixir#24]
I'm seeing
```
 {"Kernel pid terminated",application_controller,"{application_start_failure,ielixir,{bad_return,{{'Elixir.IElixir',start,[normal,[]]},{'EXIT',{undef,[{erlzmq_nif,context,[1],[]},{'Elixir.IElixir',start,2,[{file,\"lib/ielixir.ex\"},{line,13}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,ielixir,{bad_return,{{'Elixir.IElixir',start,[normal,[]]},{'EXIT',{undef,[{erlzmq_nif,context,[1],[]},{'Elixir.IElixir',start
```

I apologize if this report is naive - i'm just learning elixir.

**Comment by stochastic-thread** [comment]
@elbamos include system information, your elixir/erlang/notebook version... very little information to go on.
are you sure you followed the setup instructions correctly?

**Comment by vikrantsanghvi** [comment]
{"Kernel pid terminated",application_controller,"{application_start_failure,ielixir,{bad_return,{{'Elixir.IElixir',start,[normal,[]]},{'EXIT',{undef,[{erlzmq_nif,context,[1],[]},{'Elixir.IElixir',start,2,[{file,\"lib/ielixir.ex\"},{line,13}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,ielixir,{bad_return,{{'Elixir.IElixir',start,[normal,[]]},{'EXIT',{undef,[{erlzmq_nif,context,[1],[]},{'Elixir.IElixir',start

Crash dump is being written to: erl_crash.dump...done
Traceback (most recent call last):
  File "/Users/vsanghvi007/anaconda/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/jupyter_console/app.py", line 110, in init_shell
    client=self.kernel_client,
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 251, in __init__
    self.init_kernel_info()
  File "/Users/vsanghvi007/anaconda/lib/python2.7/site-packages/jupyter_console/ptshell.py", line 305, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request


I am getting this error even after following the instruction. Any workaround? Thanks you.

**Comment by pprzetacznik** [comment]
@elbamos @vikrantsanghvi can you test the issue one more time on the new release?
