### ISSUE TITLE
IElixer crashes after startup

### ISSUE THREAD

**Issue by AaronLain** [pprzetacznik/IElixir#56]
Hello! I've been trying to get IElixir to run but it keeps quitting as soon as it starts up via `mix test`. I have made it through the installation phase, but this one error has me absolutely stumped. 
I get this output: 
```
2020-10-17 20:44:09.178 [debug] Initializing control agent on url: tcp://127.0.0.1:42483
2020-10-17 20:44:09.178 [info] Application ielixir exited: IElixir.start(:normal, []) returned an error: shutdown: failed to start child: IElixir.Sandbox
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :elixir.string_to_quoted!/4 is undefined or private
            (elixir 1.11.0) :elixir.string_to_quoted!('import IEx.Helpers', 1, "nofile", [])
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:246: IElixir.Sandbox.eval/3
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:220: IElixir.Sandbox.prepare_clear_state/0
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:31: IElixir.Sandbox.init/1
            (stdlib 3.13.2) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13.2) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

** (Mix) Could not start application ielixir: IElixir.start(:normal, []) returned an error: shutdown: failed to start child: IElixir.Sandbox
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function :elixir.string_to_quoted!/4 is undefined or private
            (elixir 1.11.0) :elixir.string_to_quoted!('import IEx.Helpers', 1, "nofile", [])
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:246: IElixir.Sandbox.eval/3
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:220: IElixir.Sandbox.prepare_clear_state/0
            (ielixir 0.9.18) lib/ielixir/sandbox.ex:31: IElixir.Sandbox.init/1
            (stdlib 3.13.2) gen_server.erl:417: :gen_server.init_it/2
            (stdlib 3.13.2) gen_server.erl:385: :gen_server.init_it/6
            (stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

I'm running macos Catalina 10.15.7. Since I'm new to elixir I'm having trouble tracking down this particular issue and googling yields me nothing unfortunately.

**Comment by Dzol** [comment]
I have the same issue :/

**Comment by pprzetacznik** [comment]
Hi @AaronLain and @Dzol. Can you please provide me following set of information?
- `iex --version`
- `erl --version`
- `python --version`
Thanks!

**Comment by pprzetacznik** [comment]
Hi @AaronLain and @Dzol. It should work now. Please try once again.

**Comment by Dzol** [comment]
Hi :) That seems to have fixed it. Thanks a lot!
